version: '3.6'

services:
    web:
        build: .
        image: rosenmeister
        command: python3.6 manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        depends_on:
            - db
            
            
    db:
      image: postgres
      environment:
          POSTGRES_HOST_AUTH_METHOD: trust
      ports:
         - "5432:5432"
        