# Generated by Django 3.0.6 on 2020-06-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RosenmeisterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
